name: "[CI] Auto"
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  templates-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # 4.1.7
    - run: make test
  nodeadm-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # 4.1.7
    - run: cd nodeadm && make build
  nodeadm-check-generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # 4.1.7
    - run: hack/nodeadm-check-generate.sh
  nodeadm-check-vendor:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # 4.1.7
    - run: hack/nodeadm-check-vendor.sh
  nodeadm-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # 4.1.7
    - run: cd nodeadm && make test
  nodeadm-test-e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # 4.1.7
    - run: cd nodeadm && make test-e2e
